# User Task: find the RSP function in Mischief Makers and create a toml for it in this format.
# Usually includes recompiling the n_aspMain function or njpgdspMain function. Find what RSP functions are used in your game.
# n_aspMain is an example; the RSP function may be different for your game.
text_offset = 0xBCAB0
text_size = 0xE20
text_address = 0x04001080
rom_file_path = "mischiefmakers.z64"
output_file_path = "rsp/aspMain.cpp"
output_function_name = "aspMain" 
extra_indirect_branch_targets = [
    # dispatch table
    0x1118, 0x1470, 0x11DC, 0x1B38, 0x1214, 0x187C, 0x1254, 0x12D0,
    0x12EC, 0x1328, 0x140C, 0x1294, 0x1E24, 0x138C, 0x170C, 0x144C
]
