# Config file for Mischief Makers [MischiefMakersVersion] Recompilation.

[input]
# User Task: Set the game entry point
entrypoint = 0x80000400

# Paths are relative to the location of this config file.
output_func_path = "RecompiledFuncs"

# Used after symbols are dumped. Elf is used until symbols are dumped and rom is usable
#rom_file_path = "mischiefmakers.z64"

# Used after symbols are dumped. Elf file is required to get started
#symbols_file_path = "MischiefMakersRecompSyms/dump.toml"

# Enabled until the context is dumped with "--dump-context" and the recompiler is pointed to the symbols
elf_path = "mischiefmakers.elf"

relocatable_sections_path = "overlays.txt"

# Enable only when debugging recompilation issues.
#trace_mode = true

# Treat sections ending in "_bss" as zero-initialized BSS RAM.
bss_section_suffix = "_bss"

manual_funcs = []

[patches]

ignored = [
    "aspMainTextStart",
    "gspFast3DTextStart",
]

renamed = []

stubs = []

# Single-instruction patches

# Insert a manual function at a certain location based on vram. Useful for solving idle threads. 
# Two examples including a pause_wait and yield_wait:
# [[patches.hook]]
# What function does the patch go in? Look in the recompiled functions for the name of the function that contains the vram you want to patch.
# func = "func_name"
# Example function to yield in a spinning wait. Replace the original pause_self with yield_self to allow other threads to run.
# text = "pause_self(rdram);"
# VRAM location is found in the recompiled functions.
# before_vram = 0x80000000

[[patches.hook]]
func = "rmonMain_recomp"
text = "printf('TEST');"
#text = "load_overlay_by_id(0, 0x80000000)"
before_vram = 0x8009A2B8

# Yield in spinning wait.
#[[patches.hook]]
# func = "func_name"
# text = "yield_self(rdram);"
# before_vram = 0x80000000
